### ISSUE TITLE
📅 - Taiga UI 2023 roadmap

### ISSUE THREAD

**Issue by waterplea** [taiga-family/taiga-ui#3996]
Here are Taiga UI focuses on 2023

### Q1

https://www.youtube.com/watch?v=5r06heQ5HsI

### Q2

- [x] https://github.com/Tinkoff/taiga-ui/issues/1358
- [x] https://github.com/Tinkoff/taiga-ui/issues/3704
- [x] https://github.com/Tinkoff/taiga-ui/issues/3246
- [x] https://github.com/Tinkoff/taiga-ui/issues/120
- [x] [Mask related issues](https://github.com/Tinkoff/taiga-ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22scope%3A+mask%22)
- [x] [Continue improving the Editor](https://github.com/Tinkoff/taiga-ui/issues?q=is%3Aissue+is%3Aopen+label%3A%22scope%3A+editor%22)
- [x] Emphasize bugfix efforts

### Q3
- [x] https://github.com/Tinkoff/taiga-ui/issues/4710
- [x] https://github.com/Tinkoff/taiga-ui/issues/3858
- [x] https://github.com/Tinkoff/taiga-ui/issues/3539
- [x] https://github.com/Tinkoff/maskito/issues/323
- [x] Emphasize bugfix efforts and backlog reduction

### Q4

- [x] new components per internal specs (published as `@taiga-ui/experimental` until next major release).
- [x] https://github.com/Tinkoff/taiga-ui/issues/4912
- [ ] 4.0.0 with Angular bumped to v15, presumably, with standalone and finalized APIs for experimental package.
